Contactform
BenMKT/Portfolio pull request #8
Opened 2023-04-04 22:51 UTC by BenMKT

2023-04-04 23:41 UTC, adel-gu requested changes
# Status: REQUIRED CHANGES ♻️ 

Hi @Team 👋🏼 

Good job so far! 👏🏼 
There are some issues that you still need to work on to go to the next project but you are almost there! 💪🏼💪🏼💪🏼 

![](https://media0.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47f44byzj14jc88somk0nib3n5aiob98ebbt6s76mj&rid=giphy.gif&ct=g)

## Highlights
- All inputs are set as required ✅ 
- The Form is integrated with Formspree ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider:
- **Building the habit of committing always and often for each change will set you apart as professional developers 👍🏼** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 23:41 UTC, adel-gu commented on index.html
>             <ul class="drop">
- [ ] I think its structure prefared if the form holds elements that are related to the form only, it's structurally convenient to have it this way, so please consider moving both the `h1` and `p` tags outside the `form` element 👍🏼 

![Screenshot from 2023-04-05 00-08-43](https://user-images.githubusercontent.com/68030297/229942205-ec5d5180-eb8a-45b0-b0c5-4efad622f4c0.png)

2023-04-04 23:41 UTC, adel-gu commented on index.html
>             <div class="stretch">
- [ ] Please consider fixing the decorative elements in the contact section background, since this project is a good practice for your HTML and CSS skills it will be amazing if you stick to the Figma design as much as possible 💪🏼, I think this is achievable by increasing the top spacing for the contact form 👌🏼 

### Your Design
![image](https://user-images.githubusercontent.com/68030297/229943222-b65d7f8e-b24c-49da-96d6-375d98b8f341.png)

### Figma Design
![image](https://user-images.githubusercontent.com/68030297/229943288-92c40f94-9884-4a50-b91d-2507ba78b604.png)

2023-04-04 23:41 UTC, adel-gu commented on index.html
>              <li><img src="img/Ellipse 1.png" alt="Javascript"></li>
- [ ] The correct interaction styling for the `Get in touch` button is missing, please ensure adding the interaction on pressing the button following the Figma design system provided 👍🏼 

| State      | Your Design | Figma Design     |
| :---        |    :----:   |          ---: |
| Pressed   | ![Screenshot from 2023-04-05 00-22-10](https://user-images.githubusercontent.com/68030297/229944613-20a4ac79-5b01-45bc-87de-a2872b917e63.png) | ![Screenshot from 2023-04-05 00-31-17](https://user-images.githubusercontent.com/68030297/229944691-184b2e92-0f82-49cb-846d-f195e9a8e701.png)  |

2023-04-05 16:15 UTC, BenMKT commented on index.html
>              <li><img src="img/Ellipse 1.png" alt="Javascript"></li>
-Added styling to the `Get in touch` button in the contact form to resolve bug,

2023-04-05 16:54 UTC, BenMKT commented on index.html
>             <ul class="drop">
-Moved the `h1` and `p` elements from nesting in the form element to resolve the issue raised above

2023-04-05 17:18 UTC, BenMKT commented on index.html
>             <div class="stretch">
-Top spacing for the contact form increased to match Figma's design as a resolution to the above feedback.

2023-04-05 17:44 UTC, vickymarz approved these changes
Hi @BenMKT, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- good UI design ✅ 
- Form validation added ✅ 
- Form submitted properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 17:49 UTC, merged